// sveltekit-frontend/src/components/stateless/AvatarCollection.svelte
<script lang="ts">
	import Avatar from '$src/components/stateless/Avatar.svelte';

	export let avatars: { src: string; name: string }[];
</script>

<div class="avatar-collection">
	{#each avatars as avatar}
		<div class="avatar"><Avatar src={avatar.src} name={avatar.name} /></div>
	{/each}
</div>

<style>
	.avatar-collection {
		display: flex;
		flex-direction: row-reverse;
	}

	.avatar {
		margin-left: -1rem;
	}
</style>

// solidjs-frontend/src/ui-system/AvatarCollection/AvatarCollection.tsx
import { Component, For } from "solid-js";
import { Avatar } from "../";
import styles from "./AvatarCollection.module.css";

export const AvatarCollection: Component<{
  avatars: { src: string; name: string }[];
}> = (props) => {
  return (
    <div class={styles["avatar-collection"]}>
      <For each={props.avatars}>
        {(avatar) => (
          <div class={styles.avatar}>
            <Avatar src={avatar.src} name={avatar.name} />
          </div>
        )}
      </For>
    </div>
  );
};
